# Generated by Django 3.1.6 on 2021-10-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordgroup',
            name='numberOfFields',
            field=models.IntegerField(default=0),
        ),
    ]
