# Generated by Django 3.1.6 on 2021-10-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0002_recordgroup_numberoffields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordgroup',
            name='field_definitions',
            field=models.JSONField(default={}),
        ),
    ]
