# Generated by Django 3.1.6 on 2021-09-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0002_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='created_by',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
