# Generated by Django 3.1.6 on 2021-10-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0004_auto_20211008_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
        migrations.AddField(
            model_name='record',
            name='custom_fields',
            field=models.JSONField(default=dict),
        ),
    ]
